name: C/C++ CI

on:
  push:
    branches: ["branchHTTPserver"]
  pull_request:
    branches: ["branchHTTPserver"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make automake autoconf libtool devscripts build-essential
      - name: Build Program with Automake
        run: |
          ./configure
          make

      - name: make
        run: make

      - name: Build and Run Unit Test
        run: |
          ./configure
          make
          make check

      - name: QEMU install
        uses: docker/setup-qemu-action@v3

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build ls
        run: docker buildx ls

      - name: Log in to dockerhub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Dockerfile image for amd64
        run: docker build --platform=linux/amd64 -t nikolaienkodmytro/httpserv:amd64 --push .

      - name: Build Dockerfile image for arm64
        run: docker build --platform=linux/arm64 -t nikolaienkodmytro/httpserv:arm64 --push .

      - name: Create manifest
        run: docker manifest create nikolaienkodmytro/httpserv --amend nikolaienkodmytro/httpserv:amd64 --amend nikolaienkodmytro/httpserv:arm64

      - name: Push manifest to docker hub
        run: docker manifest push nikolaienkodmytro/httpserv