name: C/C++ CI

on:
  push:
    branches: ["branchAutomake"]
  pull_request:
    branches: ["branchAutomake"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make automake autoconf libtool pkg-config
      - name: Build Program with Automake
        run: |
          ./configure
          make

      - name: make
        run: make

      - name: Create distribution
        run: make dist

      - name: Upload tarball
        uses: actions/upload-artifact@v4
        with:
          name: trig_function-dist
          path: trig_function-*.tar.gz
