name: C/C++ CI

on:
  push:
    branches: ["branchMake"]
  pull_request:
    branches: ["branchMake"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make

      - name: make
        run: make
